// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_yiywu.Models;

namespace Mission06_yiywu.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    partial class MovieFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_yiywu.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("ApplicationResponse");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Romance",
                            Director = "steven",
                            Edited = true,
                            LentTo = "Eva",
                            Notes = "Best Movie of the Century",
                            Rating = "G",
                            Title = "Pride and Prejudice",
                            Year = 2006
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Comedy",
                            Director = "Tom",
                            Edited = true,
                            LentTo = "Eva",
                            Notes = "Best Comedy of the Century",
                            Rating = "G",
                            Title = "Parent Trap",
                            Year = 2000
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Inspiring",
                            Director = "Sylvie Ohayon",
                            Edited = true,
                            LentTo = "Eva",
                            Notes = "Wish it was as easy as that to get an internship",
                            Rating = "PG-13",
                            Title = "Haute Couture",
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
